worlds:
  - 'world_the_end_0'
  - 'world_the_end_1'
  - 'world_the_end_2'
  - 'world_the_end_3'
  - 'world_the_end_4'
  - 'world_the_end_5'
  - 'world_the_end_6'
  - 'world_the_end_7'
  - 'world_the_end_8'
  - 'world_the_end_9'
  - 'world_the_end_10'
  - 'world_the_end_11'
  - 'world_the_end_12'
  - 'world_the_end_13'
  - 'world_the_end_14'
  - 'world_the_end_15'
  - 'world_the_end_16'
  - 'world_the_end_17'
  - 'world_the_end_18'
  - 'world_the_end_19'
  - 'world_the_end_20'
  - 'world_the_end_21'
  - 'world_the_end_22'
  - 'world_the_end_23'
  - 'world_the_end_24'