name: RandomSpawnTp
version: @version@
main: com.tamrielnetwork.randomspawntp.RandomSpawnTp
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Teleports you to a random world spawn.
commands:
  rstp:
    description: "Main command"
    usage: "/rstp"
permissions:
  randomspawntp.rstp:
    description: "Permission to teleport"
    default: op
  randomspawntp.cooldown.bypass:
    description: "Permission to bypass cooldown"
    default: op
